### ISSUE TITLE
定時更新 keanux-personal commit

### ISSUE THREAD

**Issue by jhen0409** [Keanux/keanux-vagrant#3]
目前 keanux-personal 的連結停留在 commit 9599ca0
因此要定時去更新它

**Comment by maxchu2021** [comment]
那連結怎麼設定的？定時更新是手動還是自動？

**Comment by jhen0409** [comment]
是 submodule

手動更新:
git submodule foreach --recursive git pull origin master

**Comment by maxchu2021** [comment]
可以不管他，然後改vargant裡面的sh去pull最新版嗎?

**Comment by jhen0409** [comment]
ok
這樣似乎比較好:)

**Comment by maxchu2021** [comment]
Closed by https://github.com/Keanux/keanux-vagrant/pull/4
